version: '2.4'

services:
  react-recipes-client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    depends_on:
      - react-recipes-backend
    volumes:
      - /app/node_modules
      - ./client:/app/:delegated
  # environment:
  #   database__client: mysql
  #   database__connection__host: db
  #   database__connection__user: root
  #   database__connection__password: YOURDBPASSWORDhere
  #   database__connection__database: ghost

  react-recipes-backend:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - 4000:4000
    # depends_on:
    #   - db
    volumes:
      - /app/node_modules
      - ./server:/app/:delegated
